### ISSUE TITLE
下载不完整

### ISSUE THREAD

**Issue by Cyclin15** [o0oo1/bilibili-course-downloader#3]
基本只能下载前一两节，后面会报
'data'
第3集尚未更新
这样的错

**Comment by o0oo1** [comment]
课程链接发一下，谢谢

**Comment by Cyclin15** [comment]
https://b23.tv/QNYjgGG



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月26日(周四) 中午1:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [o0oo1/bilibili-course-downloader] 下载不完整 (Issue #3)




 
课程链接发一下，谢谢

**Comment by o0oo1** [comment]
我想课程你是购买了，那么原因就是没有正确地设置cookie，你可以去b站搜一下如何获取cookie，cookie就类似于你的一个身份标识，b站要看到这个才知道你是谁。
你如果不会操作，可以加一下我的qq：1491691290，我把我下载好的发给你

**Comment by Cyclin15** [comment]
解决方案：使用F12的网络-接口查询cookie，如果用控制台指令会获取错误cookie

错误cookie不会报错而会下载B站试看内容
